spring:
  profiles:
    active:
    - dev

--- 
spring:
  profiles: dev
    application:
      name: microservicecloud-config-elog-dev

---
spring:
  profiles: test
    application:
      name: microservicecloud-config-elog-test
